const AUTH_ACTION_TYPES = {
    // VERIFY_PHONE_PENDING: 'VERIFY_PHONE_PENDING',
    // VERIFY_PHONE_SUCCESS: 'VERIFY_PHONE_SUCCESS',
    // VERIFY_PHONE_ERROR: 'VERIFY_PHONE_ERROR',

    // VERIFY_OTP_PENDING: 'VERIFY_OTP_PENDING',
    // VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    // VERIFY_OTP_ERROR: 'VERIFY_OTP_ERROR',

    // SET_PASSWORD_PENDING: 'SET_PASSWORD_PENDING',
    // SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS',
    // SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',

    // LOGIN_PENDING: 'LOGIN_PENDING',
    // LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    // LOGIN_ERROR: 'LOGIN_ERROR',
    USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
    USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
    USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',

    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',

    COMPANY_CHECK_REQUEST: 'COMPANY_CHECK_REQUEST',
    COMPANY_CHECK_FAILURE: 'COMPANY_CHECK_FAILURE',
    COMPANY_CHECK_SUCCESS: 'COMPANY_CHECK_SUCCESS',

    PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
    PROFILE_UPDATE_FAILURE: 'PROFILE_UPDATE_FAILURE',
    PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',

    CONTACT_US_REQUEST: 'CONTACT_US_REQUEST',
    CONTACT_US_FAILURE: 'CONTACT_US_FAILURE',
    CONTACT_US_SUCCESS: 'CONTACT_US_SUCCESS',

    USER_LOGGED_OUT: 'USER_LOGGED_OUT',

    SET_USER_LANGUAGE: 'SET_USER_LANGUAGE',

    CLEAN_UP_STATE_REQUEST: 'CLEAN_UP_STATE_REQUEST',
};

export default AUTH_ACTION_TYPES;