const CALCULATOR_ACTION_TYPES = {
    TILE_JOINT_REQUEST: 'TILE_JOINT_REQUEST',
    TILE_JOINT_FAILURE: 'TILE_JOINT_FAILURE',
    TILE_JOINT_SUCCESS: 'TILE_JOINT_SUCCESS',

    MORTEL_LIST_REQUEST: 'MORTEL_LIST_REQUEST',
    MORTEL_LIST_FAILURE: 'MORTEL_LIST_FAILURE',
    MORTEL_LIST_SUCCESS: 'MORTEL_LIST_SUCCESS',

    MORTEL_JOINT_REQUEST: 'MORTEL_JOINT_REQUEST',
    MORTEL_JOINT_FAILURE: 'MORTEL_JOINT_FAILURE',
    MORTEL_JOINT_SUCCESS: 'MORTEL_JOINT_SUCCESS',

    TILE_ADHESIVE_REQUEST: 'TILE_ADHESIVE_REQUEST',
    TILE_ADHESIVE_FAILURE: 'TILE_ADHESIVE_FAILURE',
    TILE_ADHESIVE_SUCCESS: 'TILE_ADHESIVE_SUCCESS',
}
export default CALCULATOR_ACTION_TYPES;