const CART_ACTION_TYPES = {
    CART_LIST_REQUEST: 'CART_LIST_REQUEST',
    CART_LIST_FAILURE: 'CART_LIST_FAILURE',
    CART_LIST_SUCCESS: 'CART_LIST_SUCCESS',

    ADD_CART_REQUEST: 'ADD_CART_REQUEST',
    ADD_CART_FAILURE: 'ADD_CART_FAILURE',
    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',

    CART_QUANTITY_UPDATE_REQUEST: 'CART_QUANTITY_UPDATE_REQUEST',
    CART_QUANTITY_UPDATE_FAILURE: 'CART_QUANTITY_UPDATE_FAILURE',
    CART_QUANTITY_UPDATE_SUCCESS: 'CART_QUANTITY_UPDATE_SUCCESS',

    CART_DELETE_REQUEST: 'CART_DELETE_REQUEST',
    CART_DELETE_FAILURE: 'CART_DELETE_FAILURE',
    CART_DELETE_SUCCESS: 'CART_DELETE_SUCCESS',

    CART_COUNT_REQUEST: 'CART_COUNT_REQUEST',
    CART_COUNT_FAILURE: 'CART_COUNT_FAILURE',
    CART_COUNT_SUCCESS: 'CART_COUNT_SUCCESS',
}
export default CART_ACTION_TYPES;