const NEWS_ACTION_TYPES = {
  NEWS_LIST_REQUEST: 'NEWS_LIST_REQUEST',
  NEWS_LIST_FAILURE: 'NEWS_LIST_FAILURE',
  NEWS_LIST_SUCCESS: 'NEWS_LIST_SUCCESS',

  NEWS_DETAIL_REQUEST: 'NEWS_DETAIL_REQUEST',
  NEWS_DETAIL_FAILURE: 'NEWS_DETAIL_FAILURE',
  NEWS_DETAIL_SUCCESS: 'NEWS_DETAIL_SUCCESS',
};
export default NEWS_ACTION_TYPES;
