const ORDER_ACTION_TYPES = {
  ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
  ORDER_LIST_FAILURE: 'ORDER_LIST_FAILURE',
  ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',

  ORDER_AGAIN_REQUEST: 'ORDER_AGAINT_REQUEST',
  ORDER_AGAIN_FAILURE: 'ORDER_AGAIN_FAILURE',
  ORDER_AGAIN_SUCCESS: 'ORDER_AGAIN_SUCCESS',

  GET_DELIVERY_LIST_REQUEST: 'GET_DELIVERY_LIST_REQUEST',
  GET_DELIVERY_LIST_FAILURE: 'GET_DELIVERY_LIST_FAILURE',
  GET_DELIVERY_LIST_SUCCESS: 'GET_DELIVERY_LIST_SUCCESS',

  ADD_DELIVERY_DETAIL_REQUEST: 'ADD_DELIVERY_DETAIL_REQUEST',
  ADD_DELIVERY_DETAIL_FAILURE: 'ADD_DELIVERY_DETAIL_FAILURE',
  ADD_DELIVERY_DETAIL_SUCCESS: 'ADD_DELIVERY_DETAIL_SUCCESS',
};
export default ORDER_ACTION_TYPES;
