const PRODUCT_ACTION_TYPES = {
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',

    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_FAILURE: 'PRODUCT_DETAIL_FAILURE',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',

    CLEAN_UP_PRODUCT: 'CLEAN_UP_PRODUCT',
}
export default PRODUCT_ACTION_TYPES;