import { StyleSheet } from 'react-native';
import normalize from 'react-native-normalize';
import GlobalStyle from '../../style/globalstyle';

export const styles = StyleSheet.create({
  productDetailContainer: {
    paddingRight: normalize(25),
    paddingLeft: normalize(25),
    paddingTop: normalize(20),
    paddingBottom: normalize(30),
    position: 'relative',
    backgroundColor: '#fff',
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "#aaa",
    zIndex: 1111,
    opacity: 0.8
  },
  producttitleBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: normalize(3),
  },
  productdetailsTitle: {
    fontSize: 24,
    color: '#000000',
    fontFamily: GlobalStyle.fontSet.OpenSansBold,
  },
  labelProduct: {
    width: 50,
    height: 28,
  },
  productPrice: {
    fontSize: 20,
    color: '#000000',
    fontFamily: GlobalStyle.fontSet.MuseoSansRegular,
    paddingBottom: normalize(5),
  },
  cartIcon: {
    width: 50,
    height: 35,
  },
  addCartBtn: {
    width: 50,
    height: 50,
    marginTop: 10,
    backgroundColor: 'transparent',
  },
  productInnerImage: {
    borderRadius: 5,
    height: normalize(140),
    width: normalize(140),
    resizeMode: 'contain',
    marginTop: normalize(10),
  },
  productDescription: {
    fontSize: 12,
    color: '#000000',
    fontFamily: GlobalStyle.fontSet.OpenSansRegular,
    paddingTop: normalize(15),
  },
  descriptionList: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: normalize(15),
  },
  listIconContainer: {
    borderWidth: 1,
    borderColor: '#FF3A18',
    borderRadius: 7,
    marginRight: normalize(15),
    paddingLeft: normalize(7),
    paddingRight: normalize(7),
    paddingTop: normalize(3),
    paddingBottom: normalize(3),
  },
  listIcon: {
    width: 10,
    height: 17,
  },
  listTitle: {
    fontSize: 12,
    color: '#5D5D5D',
    fontFamily: GlobalStyle.fontSet.OpenSansBold,
  },
  addCart: {
    borderRadius: 4,
    backgroundColor: GlobalStyle.colorSet.orange,
    marginTop: normalize(25),
  },
  addCartTitle: {
    marginLeft: normalize(6),
    color: '#fff',
    fontFamily: GlobalStyle.fontSet.MuseoSansBold,
    fontSize: 14,
  },
  productRelatedContainer: {
    backgroundColor: '#E2E3E4',
    paddingTop: normalize(15),
    paddingRight: normalize(25),
    paddingLeft: normalize(25),
    paddingBottom: normalize(25),
    flex: 1,
  },
  relatedText: {
    fontSize: 16,
    color: '#000000',
    backgroundColor: '#E2E3E4',
    fontFamily: GlobalStyle.fontSet.OpenSansBold,
    paddingBottom: normalize(15),
  },
  cardBox: {
    padding: 0,
    borderWidth: 0.5,
    borderColor: '#000000',
    borderRadius: 5,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    marginBottom: normalize(20),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 6,
  },
  moreBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageBox: {
    width: '25%',
    paddingLeft: normalize(12),
  },
  prodImage: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: 5,
  },
  contentBox: {
    width: '50%',
    paddingLeft: normalize(15),
    paddingRight: normalize(5),
  },
  prodTitle: {
    fontSize: 14,
    color: '#000000',
    fontFamily: GlobalStyle.fontSet.OpenSansRegular,
  },
  prodPrice: {
    fontSize: 14,
    color: '#000000',
    fontFamily: GlobalStyle.fontSet.OpenSansBold,
  },
  iconBox: {
    width: '25%',
    position: 'relative',
  },
  prodLabel: {
    width: 47,
    height: 27,
    position: 'absolute',
    top: normalize(-35),
    right: normalize(9),
  },
  prodCart: {
    width: 40,
    height: 28,
    position: 'absolute',
    top: normalize(20),
    right: normalize(1),
  },
  dotSlide: {
    width: 13,
    height: 13,
    borderRadius: 50,
    marginHorizontal: 0,
    padding: 0,
    margin: 0,
    backgroundColor: '#fff',
    borderColor: '#000',
    borderWidth: 1,
  },
  dotSlideBox: {
    position: 'absolute',
    bottom: 15,
    padding: 0,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingVertical: 0,
  },

  productInfo: {
    fontSize: 16,
    color: GlobalStyle.colorSet.black,
    fontFamily: GlobalStyle.fontSet.OpenSansRegular,
  },
  quantityBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  productInfoBox: {
    marginTop: 10,
    borderColor: '#eee',
    borderWidth: 1,
    padding: 10,
  },
  colorTitle: {
    fontSize: 16,
    color: GlobalStyle.colorSet.black,
    fontFamily: GlobalStyle.fontSet.OpenSansBold,
    marginBottom: 15,
  },
  colorName: {
    fontSize: 14,
    color: GlobalStyle.colorSet.black,
    fontFamily: GlobalStyle.fontSet.OpenSansRegular,
    textAlign: 'center'
    // marginBottom: 5,
  },
  selectImg: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#ddd'
  },
  checkbox: {
    // paddingTop: normalize(15),
    paddingBottom: normalize(0),
    paddingLeft: normalize(0),
    paddingRight: normalize(0),
    backgroundColor: 'transparent',
    borderWidth: 0,
    margin: 0,
  },
  uncheck: {
    width: 15,
    height: 15,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#43464B',
    borderRadius: 2,
  },
  check: {
    width: 9,
    height: 9,
    backgroundColor: '#43464B',
    margin: 1,
    borderRadius: 2,
  },
  itemBox: {
    marginBottom: 20,
    marginRight: 10,
  },
  checkContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  productContainer: {
    // marginTop: 10,
    borderWidth: 1,
    borderColor: '#000000',
    borderSize: 1,
    color: '#FFFFFF',
    backgroundColor: '#fff',
    borderRadius: 5,
    margin: normalize(5, 'height'),
    height: 50,
    marginBottom: 20,
    position: 'relative',
    // zIndex: 1,
  },
  listBox: {
    marginTop: normalize(-3),
    position: 'absolute',
    width: 'auto',
    backgroundColor: '#fff',
    top: normalize(50, 'height'),
    left: normalize(1, 'height'),
    right: normalize(1, 'height'),
    borderBottomWidth: 1,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 6,
  },
  boxText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#000',
    textTransform: 'uppercase',
    // marginLeft: normalize(7),
  },
  boxRedText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFF',
  },
  selectPro: {
    lineHeight: 25,
  },
  listText: {
    fontSize: 12,
    fontWeight: 'normal',
    color: '#FF3A18',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    borderBottomWidth: 0,
    borderColor: '#000000',
    borderWidth: 1,
  },
  tileBox: {
    flex: 1,
    flexDirection: 'row',
    padding: 10,
    borderColor: '#000000',
    borderSize: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commonBox: {
    //flex: 1,
    borderColor: '#000000',
    borderSize: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: normalize(5, 'height'),
  },
  ordrBtn: {
    marginTop: normalize(20),
  },
  calculateBtn: {
    backgroundColor: 'black',
    borderColor: 'black',
    borderWidth: 2,
  },
  resetBtn: {
    backgroundColor: 'white',
    borderColor: 'black',
    borderWidth: 2,
  },
  proText: {
    fontSize: 14,
    lineHeight: 25,
    color: '#FF3A18',
    marginEnd: 5,
  },
  qtyText: {
    fontSize: 16,
    color: '#9A9B9F',
  },
  elevation: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 6,
  },
  WhiteBox: {
    flex: 0,
    flexDirection: 'column',
    flexBasis: '45%',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    marginBottom: normalize(20),
    padding: normalize(10),
  },
  RedBox: {
    flex: 0,
    flexDirection: 'column',
    flexBasis: '45%',
    borderWidth: 1,
    borderColor: '#FF3A18',
    borderRadius: 5,
    marginBottom: normalize(20),
    padding: normalize(10),
    backgroundColor: '#FF3A18',
  },
  bottomBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: normalize(50),
    marginLeft: normalize(5),
    marginRight: normalize(5),
  },
  orderText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
    textTransform: 'uppercase',
  },
  calculateText: {
    color: 'white',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  resetText: {
    color: 'black',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  orderBox: {
    marginLeft: normalize(5),
    marginRight: normalize(5),
  },
  resetBox: {
    flex: 0,
    marginRight: 15,
    flexBasis: '45%',
  },
  calculateBox: {
    flex: 0,
    flexBasis: '45%',
    marginLeft: 15,
  },
  selectItem: {
    //flex: 1,
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  boxTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  boxInnerText: {
    lineHeight: 35,
    fontSize: 18,
  },
  redBoxTop: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  redInnerText: {
    lineHeight: 35,
    fontSize: 18,
    color: 'white',
    fontSize: 22,
  },
});
