import {StyleSheet} from 'react-native';
import normalize from 'react-native-normalize';

export const styles = StyleSheet.create({
  productContainer: {
    // marginTop: 10,
    borderWidth: 1,
    borderColor: '#000000',
    borderSize: 1,
    color: '#FFFFFF',
    backgroundColor: '#fff',
    borderRadius: 5,
    margin: normalize(5, 'height'),
    height: 50,
    marginBottom: 20,
    position: 'relative',
    // zIndex: 1,
  },
  listBox: {
    marginTop: normalize(-3),
    position: 'absolute',
    width: 'auto',
    backgroundColor: '#fff',
    top: normalize(50, 'height'),
    left: normalize(1, 'height'),
    right: normalize(1, 'height'),
    borderBottomWidth: 1,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 6,
  },
  boxText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#000',
    textTransform: 'uppercase',
    // marginLeft: normalize(7),
  },
  boxRedText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFF',
  },
  selectPro: {
    lineHeight: 25,
  },
  listText: {
    fontSize: 12,
    fontWeight: 'normal',
    color: '#FF3A18',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    borderBottomWidth: 0,
    borderColor: '#000000',
    borderWidth: 1,
  },
  tileBox: {
    flex: 1,
    flexDirection: 'row',
    padding: 10,
    borderColor: '#000000',
    borderSize: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commonBox: {
    //flex: 1,
    borderColor: '#000000',
    borderSize: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: normalize(5, 'height'),
  },
  ordrBtn: {
    marginTop: normalize(20),
  },
  calculateBtn: {
    backgroundColor: 'black',
    borderColor: 'black',
    borderWidth: 2,
  },
  resetBtn: {
    backgroundColor: 'white',
    borderColor: 'black',
    borderWidth: 2,
  },
  proText: {
    fontSize: 14,
    lineHeight: 25,
    color: '#FF3A18',
    marginEnd: 5,
  },
  qtyText: {
    fontSize: 16,
    color: '#9A9B9F',
  },
  elevation: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 6,
  },
  WhiteBox: {
    flex: 0,
    flexDirection: 'column',
    flexBasis: '45%',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    marginBottom: normalize(20),
    padding: normalize(10),
  },
  RedBox: {
    flex: 0,
    flexDirection: 'column',
    flexBasis: '45%',
    borderWidth: 1,
    borderColor: '#FF3A18',
    borderRadius: 5,
    marginBottom: normalize(20),
    padding: normalize(10),
    backgroundColor: '#FF3A18',
  },
  bottomBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: normalize(50),
    marginLeft: normalize(5),
    marginRight: normalize(5),
  },
  orderText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
    textTransform: 'uppercase',
  },
  calculateText: {
    color: 'white',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  resetText: {
    color: 'black',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  orderBox: {
    marginLeft: normalize(5),
    marginRight: normalize(5),
  },
  resetBox: {
    flex: 0,
    marginRight: 15,
    flexBasis: '45%',
  },
  calculateBox: {
    flex: 0,
    flexBasis: '45%',
    marginLeft: 15,
  },
  selectItem: {
    //flex: 1,
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  boxTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  boxInnerText: {
    lineHeight: 35,
    fontSize: 18,
  },
  redBoxTop: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  redInnerText: {
    lineHeight: 35,
    fontSize: 18,
    color: 'white',
    fontSize: 22,
  },
});
