export default {
  home: {
    login: 'LOGIN_NL',
    register: 'REGISTER_NL',
    continue: 'CONTINUE WITHOUT LOGIN_NL',
    quality: 'Quality',
    service: 'Service',
    belgian: 'Belgian',
  },
  redLabel: {
    the: "The",
    red: "Red",
    label: "Label"
  },
  login: {
    welcome: 'Welcome to the Diamur app',
    description: 'Please log in below or create an account.',
    formTitle: 'Please fill in your details:',
    login: 'LOGIN',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'forgot password',
    createAccount: 'Creat an account',
  },
  register: {
    welcome: 'Welcome to the Diamur app',
    description:
      'Om u te registreren in ons systeem. Vragen wij u volgende gegevens in te vullen of aan te passen indien nodig.',
    step2Description:
      'Omdat u nog niet gekend bent in ons systeem. Vragen wij u volgende gegevens',
    companyNumber: 'Company number',
    btnRegister: 'REGISTRATION REQUESTS',
    back: 'Terug',
    activity: "Activity",
    floorer: 'Floorer',
    mason: 'Mason',
    contractor: 'Contractor',
    headOffice: 'Head office',
    termsCondition: 'I agree with the terms and conditions.',
    uniqueId: 'Please enter your unique email and password.',
    Ovalidation: 'Please enter 0 at first place',
    hiSkkills: "Hi Skkills",
    welcomeDiamurApp: "Welcome to the Diamur app.",
    yourCompanyNumber: 'Your company number',
    alreadyKnownOurSystem: "is already known in our system.",
    step3SubTitle1: 'To confirm that this is you, we have sent an email to the registered email address',
    step3SubTitle2: 'Please open this mail and click on the activation link.',
    step3SubTitle3: "Do you no longer have access to this e-mail address?",
    step3SubTitle4: 'Please contact us on:',
    step5title: 'Dag Skkills',
    step5title1: "Welkom bij de Diamur app.",
    step5title2: 'De bevestiging voor uw account is voltooid. Wij sturen u door naar uw profiel.',
    step5title3: 'YOUR PROFILE HAS BEEN CONFIRMED!'
  },
  tabHome: {
    orders: 'Orders',
    pending: 'Pending',
    orderCompleted: 'Order completed',
  },
  buttons: {
    viewAllProducts: 'View All Products',
    shoppingCart: 'Shopping cart',
    viewProduct: 'View product',
    yourProducts: 'Your Products',
    allProducts: 'All Products',
    continueShopping: 'CONTINUE SHOPPING',
    reOrder: 'RE-ORDER',
    continue: 'Continue',
    confirmYourOrder: 'Confirm Your Order',
    viewOrderHistory: 'View Order History',
    confirm: 'Confirm',
    send: 'Send',
    askQuestion: 'Ask your question to Diamur',
    search: 'Search',
    changeInformation: 'CHANGE YOUR INFORMATION',
    changePassword: 'WACHTWOORD WIJZIGEN',
    resend: 'Resend The Link',
    save: 'Save',
    reset: 'Reset',
    calculate: 'Calculate',
    orderNow: 'Order Now',
  },
  tabArchieve: {
    latestOrders: 'Latest orders :',
  },
  tabCart: {
    pending: 'Pending',
    orderNo: 'Order nr',
    orderedOn: 'Ordered on',
    bill: 'Bill:',
    download: 'DOWNLOADEN',
    sent: 'Verzonden:',
    productOrdered: 'Products ordered:',
    total: 'Total',
    exclude: 'excl. transport',
    back: 'vorig scherm',
    orderOverview: 'Order overview',
    deliveryAddress: 'Delivery address',
    ownDepot: 'Own depot:',
    additionComment: 'Addition comment:',
    payment: 'Payment:',
    payNow: 'Pay now',
    payOnCredit: 'Pay on credit:',
    thankYou: 'Thank you for your order!',
    failure: 'Something went wrong',
    interested: 'Are you also interested in other products?',
    range: 'View our product range here.',
    deliveryInformation: 'Delivery information',
    billingAddress: 'Delivery to billing address',
    otherAddress: 'Delivery to other address',
    deliveryFrom: 'Delivery from',
    newYardAddress: 'New yard address',
    additionalComment: 'Additional comment:',
    address: 'Address',
    siteAddresses: 'Site addresses',
    streetZip: 'Street + number, Zip code + city',
    addressInput: 'Adres + nr',
    city: 'City',
    zipCode: 'Zip Code',
    pieces: 'Pieces',
    transpotationCost: 'Transportation costs',
    palletCost: 'Palette cost'
  },
  contact: {
    contactUs: 'Contact us',
    contactInformation: 'Contact information',
    contactAddress: 'Diamur nv Zwarte Weg 47 - Kade 367 BE 2030 Antwerpen',
    contactNumber: 'T +32 3 544 15 20',
    contactFax: 'F +32 3 544 15 27',
    contactEmail: 'info@diamur.be',
    inputFields: {
      company: 'Company ',
      companyPlaceholder: 'bv: Diamur',
      name: 'Name ',
      namePlaceholder: 'bv: Peter Piceu',
      email: 'Email ',
      emailPlaceholder: 'bv: info@diamur.be',
      street: 'Street + nr ',
      streetPlaceholder: 'bv: Zwarte Weg 47',
      zipCity: 'Zip code + City ',
      zipCityPlaceholder: '2030 Antwerpen',
      telephone: 'Telephone ',
      telephonePlaceholder: '+32 3 544 15 20',
      message: 'Message ',
      messagePlaceholder: 'Uw boodschap',
      questions: ' I have a question concerning ',
      questionsPlaceholder: 'Request for delivery / technical advice / sales …',
    },
  },
  faqs: {
    faqsHeading: 'Frequently asked questions',
    backFaqs: 'BACK TO FREQUENTLY ASKED QUESTIONS',
    noDataFound: 'No Data Found'
  },
  menu: {
    menuHeading: 'Menu',
  },
  news: {
    newsHeading: 'News',
  },
  newsDetail: {
    otherArticles: 'Other interesting articles',
    backOverview: 'Back to overview',
    otherProducts: 'Other Products',
  },
  productFilter: {
    assortment: 'Assortment',
    searchPlaceholder: 'Type a product name to search for it',
  },
  profile: {
    township: 'Township',
    street: 'Street',
    registredOffice: 'Maatschappelijke zetel',
    profile: 'Profile',
    accountNumber: 'Account Number',
    yourDetails: 'Your Details',
    enterPassword: 'Please enter your password here',
    changePassword: "CHANGE PASSWORD",
    cancel: "CANCEL"
  },
  resendLink: {
    emailAddress: 'Your email address',
  },
  calculator: {
    lengthOfJoint: 'LENGTH OF JOINT',
    tegelvoeg: 'Tegelvoeg',
    mortelcalculator: 'Mortelcalculator',
    voegmortelcalculator: 'Voegmortelcalculator',
    tegellijmcalculator: 'Tegellijmcalculator',
    calculatorMessage: 'houd hier rekening mee voordat u onze rekentool gebruikt.',
    selectProduct: 'SELECT A PRODUCT',
    totalSurface: 'Total Surface',
    totalArea: 'Total Area',
    tileLength: 'Tile Length',
    widthLine: 'WIDTH OF LINE',
    widthGrout: 'WIDTH OF GROUT',
    depthGrout: 'DEPTH OF THE GROUT',
    weightGrout: 'WEIGHT OF GROUT',
    heightGrout: 'Height of The Grout',
    mortel: 'MORTEL',
    groutingMortar: 'KG GROUTING MORTAR',
    titleAdhesive: 'KG TILE ADHESIVE',
    stoneLength: 'STONE LENGTH',
    depthStone: 'DEPTH STONE',
    stoneHeight: 'STONE HEIGHT',
  },
  productDetail: {
    priceDecreaseStuck: 'price decrease per stuck',
    purchasePricePackage: 'purchase price per package',
    addBasket: 'Add to Basket',
    colors: "colors"
  }
};
