import { StyleSheet, Platform } from 'react-native';
import normalize from 'react-native-normalize';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    backgroundColor: 'white',
    paddingTop: normalize(10, 'height'),
    marginTop: normalize(45, 'height'),
    //marginBottom: normalize(30, 'height'),
    paddingLeft: '5%',
    paddingRight: '5%',
  },
  scrollContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topButtonSection: {
    marginBottom: 0,
    marginTop: 0,
    backgroundColor: '#fff',
    position: 'absolute',
    zIndex: 1,
    width: '100%',
  },
  menuButton: {
    backgroundColor: '#FF3A18',
    padding: 3,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 5,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 5,
    position: 'relative',
  },
  submenuButton: {
    marginTop: -4,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 0,
    paddingRight: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 5,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 5,
    borderColor: '#FF3A18',
    borderWidth: 1,
    borderTopColor: 'transparent',
    width: '100%',
  },
  topButtonIcon: {
    marginLeft: 15,
    color: '#FFFFFF',
  },
  title: {
    textDecorationLine: 'underline',
    color: '#FF3A18',
    paddingLeft: 5,
    fontSize: 11,
    marginTop: normalize(10, 'height'),
    marginBottom: normalize(10, 'height'),
  },

  modalTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: normalize(10, 'height'),
  },
  modalSubTitle: {
    fontSize: 12,
    fontWeight: 'normal',
    color: '#000',
    marginBottom: normalize(15, 'height'),
  },
  TextModal: {
    margin: normalize(20, 'height'),
  },
  calItem: {
    color: '#FF3A18',
    fontWeight: 'normal',
    fontSize: 13,
    textAlign: 'center',
  },
  closeToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'absolute',
    right: normalize(-15, 'height'),
    zIndex: 111,
    top: normalize(-5, 'height'),
  },
  modalBody: {
    marginTop: normalize(10, 'height'),
  },
  calList: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  inputKeyItem: {
    fontSize: 40,
    lineHeight: 50,
  },
  inputKeyBox: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: normalize(30),
  },
  inputValue: {
    fontSize: 40,
    textAlign: 'center',
    color: 'black',
    opacity: 1,
  },
  keyUnit: {
    fontSize: 26,
    color: '#9A9B9F',
  },
  inputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  totalArea: {
    fontSize: 26,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  closeInput: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  closeBox: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#43464B',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    marginTop: Platform.OS === "ios" ? 40 : 0,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
  },
  nextBtnTitle: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  nextBtn: {
    borderRadius: 0,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    height: 60,
  },
  closeText: {
    fontSize: 16,
    color: 'white',
    marginRight: normalize(15, 'height'),
    fontWeight: 'bold',
  },
  inputOverlay: {
    padding: 0,
    marginTop: 0,
  },
  nextContainer: {
    width: '100%',
    marginLeft: 0,
    marginRight: 0,
    borderRadius: 0,
  },
  totalTop: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: normalize(20),
  },
  innerOverlay: {
    backgroundColor: '#fff',
    marginLeft: normalize(21),
    marginRight: normalize(21),
    paddingLeft: normalize(25),
    paddingRight: normalize(25),
    paddingTop: normalize(15),
    paddingBottom: normalize(15),
  },
});
